### ISSUE TITLE
Create a module to "handle" the 5 photoresistors

### ISSUE THREAD

**Issue by liquiddandruff** [SFUSatClub/balloon1#5]
This class will derive from the `Module` class and should be straightforward to implement. Here are some things it will need to do:
- Read the analog values from the pins belonging to the 5 photoresistors
- Store these values
- Override the virtual method `const char* Module::dataToPersist()` and return a c style string to be written to the sd card--the format's up to you!

Check how the other modules are implemented for some examples, and feel free to dive in!

**Comment by hyyl** [comment]
Was just about to start on this.

For a standard module string format, might I suggest the comma delimited:
`<timestamp>, <sensor type>, <sort of sensor data (eg. pressure, sensorno)>, <value>\n`
We could implement it so that when recovering data from the file, if a field is left blank, it grabs from the last value it was previously specified as.

**Comment by liquiddandruff** [comment]
Closing since implemented by @hyyl in b79f147ad
